# Generated by Django 4.2.5 on 2024-05-22 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_List', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the to-do item', max_length=100)),
                ('details', models.TextField(help_text='Details about the to-do item')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of the to-do item')),
            ],
            options={
                'verbose_name': 'To-Do List',
                'verbose_name_plural': 'To-Do Lists',
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Todo_List',
        ),
    ]
